### ISSUE TITLE
Integrating with multiple devices(weight machine, glucose machine, blood pressure device)

### ISSUE THREAD

**Issue by Naveen-g09** [friyiajr/BLESampleExpo#8]
👋 Hi there,

I'm intrigued by your repository and its device scanning capabilities. However, I'm curious to know if it's possible to extend this functionality to support multiple devices simultaneously.

Extension Query: Can your solution scan for multiple devices concurrently?
Appreciation for Your Work: Loved your YouTube video! Subscribed for more. But I still have questions, especially regarding fetching data from multiple devices.
Request for Assistance:
Could you provide insights or code snippets on implementing device scanning for multiple devices? Your guidance would be highly appreciated!

Looking forward to diving deeper into your repository.

**Comment by friyiajr** [comment]
Hi @Naveen-g09 I am happy you enjoyed the video 🙂! 

Unfortunately, I've never actually encountered a situation where you've had to have multiple devices connected at the same time. Because I haven't handled this use case, I don't know how you would proceed with connecting multiple devices simultaneously.
